---

queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      # TODO: this needs t be switched to github actions
      - label!=no-mergify

pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=2'
      # We have to duplicate these because mergify won't allow us to use an
      # anchor
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        update_method: rebase
        name: default
