# Config file for automatic testing at travis-ci.org

language: python

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37

# Command to run tests, e.g. python setup.py test
script: tox

